repos:
  - hooks:
      - args:
          - --remove-all-unused-imports
          - --in-place
        id: autoflake
    repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: debug-statements
      - id: check-toml
      - id: trailing-whitespace
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: name-tests-test
        args: ["--django"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - args:
          - -v
        id: black
        require_serial: true
        name: black
        entry: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - args:
          - --py310-plus
        id: pyupgrade
